version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "gunicorn --bind 0.0.0.0:8000 --reload stripetest.wsgi:application"
    env_file:
      - ./.env
    volumes:
      - ./stripetest/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge